/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tomas' at '4/24/17 5:21 PM' with Gradle 2.10
 *
 * @author tomas, @date 4/24/17 5:21 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
